/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package jlitec;

import jlitec.command.CommandType;
import net.sourceforge.argparse4j.ArgumentParsers;
import net.sourceforge.argparse4j.inf.ArgumentParserException;

public class App {
  /**
   * Main class of the app.
   *
   * @param args command-line arguments
   */
  public static void main(String[] args) {
    final var parser =
        ArgumentParsers.newFor("jlitec")
            .build()
            .defaultHelp(true)
            .description("Compiler for the JLite language.");

    final var subparsers = parser.addSubparsers().help("sub-command help").dest("subcommand");

    for (final var type : CommandType.values()) {
      final var subparser =
          subparsers.addParser(type.name().toLowerCase()).help(type.command.helpMessage());
      type.command.setUpArguments(subparser);
    }

    try {
      final var parsed = parser.parseArgs(args);
      CommandType.run(parsed);
    } catch (ArgumentParserException e) {
      parser.handleError(e);
    }
  }
}
