/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package jlitec;

import jlitec.command.CommandType;
import net.sourceforge.argparse4j.ArgumentParsers;
import net.sourceforge.argparse4j.inf.ArgumentParserException;

public class App {
  /**
   * Main class of the app.
   *
   * @param args command-line arguments
   */
  public static void main(String[] args) {
    var parser =
        ArgumentParsers.newFor("jlitec")
            .build()
            .defaultHelp(true)
            .description("Compiler for the JLite language.");

    var subparsers = parser.addSubparsers().help("sub-command help").dest("subcommand");

    var lexerParser =
        subparsers
            .addParser(CommandType.LEXER.name().toLowerCase())
            .help("Show the result of lexing the source code for debugging.");
    lexerParser.addArgument("filename").type(String.class).help("input filename");

    try {
      var parsed = parser.parseArgs(args);
      CommandType.run(parsed);
    } catch (ArgumentParserException e) {
      parser.handleError(e);
    }
  }
}
