/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package jlitec;

import org.junit.Test;

public class AppTest {
  @Test
  public void testApp() {
    App.main(new String[0]);
  }
}
